# Generated by Django 5.2.6 on 2025-10-06 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_pessoa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='telefone',
            field=models.CharField(max_length=30, null=True, verbose_name='Telefone'),
        ),
    ]
