# Generated by Django 5.2.6 on 2025-10-14 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_produto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='cpf',
            field=models.CharField(max_length=15, unique=True, verbose_name='CPF'),
        ),
    ]
